### PR TITLE
Fix static mode visibility injection when annotation present

### LINKED ISSUE #619: cannot use @Override and @Deprecated in static mode
I just updated Processing for version 4.1.1 and now when I run sketch when there is 
`@Override` `@Deprecated` inside `class` Processing don't run, that's a regression ? or there is a goal behind that ?
Before that's work fine withe processing 4.0b7... and all the version before that from 1.5.1

the console return:
```
Cannot find a class or type named @Overridepublic...
```

or 
```
Cannot find a class or type named @Deprecatedpublic...
```

And always bravo for the Processing Team !!!!

### PR DESCRIPTION
**Pull request by sampottinger**
Closes #619 - There is a problem with adding public to members when wrapping in “static” mode processing sketches introduced by removing the leading space in #609. Requires preproc to look for leading annnotations before injecting visibility modifier. Apologies @benfry and @knupel.

### CODE REVIEW

File: java/src/processing/mode/java/preproc/PdeParseTreeListener.java [hunk 1]
```diff
@@ -591,7 +591,7 @@ public void exitMethodDeclaration(ProcessingParser.MethodDeclarationContext ctx)
       if (annoationPoint == null) {
         insertBefore(possibleModifiers.getStart(), "public ");
       } else {
-        insertAfter(annoationPoint.getStop(), "public ");
+        insertAfter(annoationPoint.getStop(), " public ");
```
Comment (sampottinger) [inline java/src/processing/mode/java/preproc/PdeParseTreeListener.java]: @benfry this is the actual fix. Everything else in this PR is just adding additional tests to prevent regressions.
